### ISSUE TITLE
executor-p2rank/Dockerfile: build fails

### ISSUE THREAD

**Issue by luk27official** [cusbg/prankweb#132]
The current `executor-p2rank/Dockerfile` fails to build.

The issue is with the `openjdk-17-jre-headless` package, which produces the following error when building the app via `docker-compose build`:

```
...
#0 87.10 Setting up ca-certificates-java (20230103) ...
#0 87.31 Exception in thread "main" java.lang.InternalError: Error loading java.security file
#0 87.31        at java.base/java.security.Security.initialize(Security.java:106)
#0 87.31        at java.base/java.security.Security$1.run(Security.java:84)
#0 87.31        at java.base/java.security.Security$1.run(Security.java:82)
#0 87.31        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
#0 87.31        at java.base/java.security.Security.<clinit>(Security.java:82)
#0 87.31        at java.base/sun.security.jca.ProviderList.<init>(ProviderList.java:178)
#0 87.31        at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:96)
#0 87.31        at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:94)
#0 87.31        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
#0 87.31        at java.base/sun.security.jca.ProviderList.fromSecurityProperties(ProviderList.java:93)
#0 87.31        at java.base/sun.security.jca.Providers.<clinit>(Providers.java:55)
#0 87.31        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:156)
#0 87.31        at java.base/java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:193)
#0 87.31        at org.debian.security.KeyStoreHandler.<init>(KeyStoreHandler.java:50)
#0 87.31        at org.debian.security.UpdateCertificates.<init>(UpdateCertificates.java:65)
#0 87.31        at org.debian.security.UpdateCertificates.main(UpdateCertificates.java:51)
#0 87.34 dpkg: error processing package ca-certificates-java (--configure):
#0 87.34  installed ca-certificates-java package post-installation script subprocess returned error exit status 1
#0 87.34 dpkg: dependency problems prevent configuration of openjdk-17-jre-headless:amd64:
#0 87.34  openjdk-17-jre-headless:amd64 depends on ca-certificates-java (>= 20190405~); however:
#0 87.34   Package ca-certificates-java is not configured yet.
#0 87.34
#0 87.34 dpkg: error processing package openjdk-17-jre-headless:amd64 (--configure):
#0 87.34  dependency problems - leaving unconfigured
#0 87.34 Processing triggers for libc-bin (2.36-9) ...
#0 87.36 Processing triggers for ca-certificates (20230311) ...
#0 87.37 Updating certificates in /etc/ssl/certs...
#0 88.47 0 added, 0 removed; done.
#0 88.47 Running hooks in /etc/ca-certificates/update.d...
#0 88.49 done.
#0 88.52 Errors were encountered while processing:
#0 88.52  ca-certificates-java
#0 88.52  openjdk-17-jre-headless:amd64
#0 88.55 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
failed to solve: executor failed running [/bin/sh -c apt-get update   && apt-get -y --no-install-recommends install   wget curl   python3 python3-pip python3-venv   openjdk-17-jre-headless   libgomp1 vim]: exit code: 100
```

A workaround to this is to install `default-jre` instead of the `openjdk-17-jre-headless` and PrankWeb seems to work. Still, I feel like we should discuss this and have a further look into the problem before creating a PR.

**Comment by luk27official** [comment]
There have been no issues with this yet, if needed, this may be reopened later.
