### ISSUE TITLE
Failed to predict 7bv2

### ISSUE THREAD

**Issue by davidhoksza** [cusbg/prankweb#27]
```
10/22/2020 15:16:51 [INFO] - Preparing structure ...
10/22/2020 15:16:51 [DEBUG] - Downloading 'https://files.rcsb.org/download/7bv2.pdb' to '/data/p2rank/task/database/v2-conservation/7bv2_A,B,C,P,T/working/structure-raw.pdb' ...
10/22/2020 15:16:51 [DEBUG] - Starting new HTTPS connection (1): files.rcsb.org:443
10/22/2020 15:16:52 [DEBUG] - https://files.rcsb.org:443 "GET /download/7bv2.pdb HTTP/1.1" 200 167677
10/22/2020 15:16:52 [DEBUG] - Reading chains ...
/usr/local/lib/python3.7/dist-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 9455.
PDBConstructionWarning,
/usr/local/lib/python3.7/dist-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain P is discontinuous at line 9468.
PDBConstructionWarning,
/usr/local/lib/python3.7/dist-packages/Bio/PDB/StructureBuilder.py:92: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 9492.
PDBConstructionWarning,
10/22/2020 15:16:52 [DEBUG] - Reading chains ... done
10/22/2020 15:16:52 [DEBUG] - Executing '/opt/protein-utils/bin/protein-utils -a filter-by-chain --structure /data/p2rank/task/database/v2-conservation/7bv2_A,B,C,P,T/working/structure-raw.pdb --output /data/p2rank/task/database/v2-conservation/7bv2_A,B,C,P,T/working/structure.pdb --chains T,C,P,A,B'
15:16:53 [main] INFO cz.siret.protein.utils.ApplicationEntry - Using action: filter-by-chain
15:16:53 [main] WARN o.b.nbio.structure.align.util.UserConfiguration - Could not read dir from system property PDB_DIR or environment variable PDB_DIR, using system's temp directory /tmp
15:16:53 [main] INFO o.b.nbio.structure.align.util.UserConfiguration - Could not read cache dir from system property PDB_CACHE_DIR or environment variable PDB_CACHE_DIR, using PDB directory instead /tmp/
15:16:53 [main] INFO org.biojava.nbio.structure.io.PDBFileParser - Could not parse revision date string ''.
15:16:53 [main] INFO org.biojava.nbio.structure.io.PDBFileParser - Could not parse revision date string ''.
15:16:53 [main] INFO org.biojava.nbio.structure.io.PDBFileParser - Could not parse revision date string ''.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/opt/protein-utils/lib/jaxb-impl-2.3.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
15:16:55 [main] INFO cz.siret.protein.utils.ApplicationEntry - Finished in 00:00:02
10/22/2020 15:16:55 [INFO] - Preparing structure ... done
10/22/2020 15:16:55 [DEBUG] - Path: /data/p2rank/task/database/v2-conservation/7bv2_A,B,C,P,T/working/structure.pdb
10/22/2020 15:16:55 [DEBUG] - Chains: T C P A B
10/22/2020 15:16:55 [DEBUG] - Executing '/opt/protein-utils/bin/protein-utils -a extract-chain-sequence --structure /data/p2rank/task/database/v2-conservation/7bv2_A,B,C,P,T/working/structure.pdb --output /data/p2rank/task/database/v2-conservation/7bv2_A,B,C,P,T/working/conservation-T/sequence.fasta --chain T'
15:16:55 [main] INFO cz.siret.protein.utils.ApplicationEntry - Using action: extract-chain-sequence
15:16:55 [main] WARN o.b.nbio.structure.align.util.UserConfiguration - Could not read dir from system property PDB_DIR or environment variable PDB_DIR, using system's temp directory /tmp
15:16:55 [main] INFO o.b.nbio.structure.align.util.UserConfiguration - Could not read cache dir from system property PDB_CACHE_DIR or environment variable PDB_CACHE_DIR, using PDB directory instead /tmp/
15:16:55 [main] INFO org.biojava.nbio.structure.io.PDBFileParser - Entity information (COMPOUND record) not found in file. Will assign entities heuristically
15:16:56 [main] ERROR cz.siret.protein.utils.ApplicationEntry - Action execution failed
15:16:56 [main] INFO cz.siret.protein.utils.ApplicationEntry - Reason
cz.siret.protein.utils.action.ActionFailed: Missing chain: T
at cz.siret.protein.utils.action.ChainToSequence.getChainSequence(ChainToSequence.java:19)
at cz.siret.protein.utils.command.StructureToFasta.saveSequence(StructureToFasta.java:78)
at cz.siret.protein.utils.command.StructureToFasta.execute(StructureToFasta.java:64)
at cz.siret.protein.utils.command.StructureToFasta.execute(StructureToFasta.java:20)
at cz.siret.protein.utils.ApplicationEntry.executeAction(ApplicationEntry.java:243)
at cz.siret.protein.utils.ApplicationEntry.executeAction(ApplicationEntry.java:204)
at cz.siret.protein.utils.ApplicationEntry.run(ApplicationEntry.java:55)
at cz.siret.protein.utils.ApplicationEntry.main(ApplicationEntry.java:41)
15:16:56 [main] INFO cz.siret.protein.utils.ApplicationEntry - Finished in 00:00:00
Traceback (most recent call last):
File "/opt/p2rank-runtime/run_p2rank_task.py", line 359, in <module>
main(_read_arguments())
File "/opt/p2rank-runtime/run_p2rank_task.py", line 64, in main
structure_file, chains, configuration, arguments)
File "/opt/p2rank-runtime/run_p2rank_task.py", line 190, in prepare_conservation
return compute_from_structure(structure_file, chains, arguments)
File "/opt/p2rank-runtime/run_p2rank_task.py", line 236, in compute_from_structure
for chain in chains
File "/opt/p2rank-runtime/run_p2rank_task.py", line 236, in <dictcomp>
for chain in chains
File "/opt/p2rank-runtime/run_p2rank_task.py", line 255, in compute_from_structure_for_chain
conservation.compute_conservation(fasta_file, working_dir, target_file)
File "/opt/p2rank-runtime/conservation.py", line 57, in compute_conservation
compute_msa(input_file, working_dir, msa_file)
File "/opt/p2rank-runtime/conservation.py", line 64, in compute_msa
sequences = _read_fasta_file(fasta_file)
File "/opt/p2rank-runtime/conservation.py", line 84, in _read_fasta_file
with open(input_file) as in_stream:
FileNotFoundError: [Errno 2] No such file or directory: '/data/p2rank/task/database/v2-conservation/7bv2_A,B,C,P,T/working/conservation-T/sequence.fasta'
```

**Comment by skodapetr** [comment]
The issue is that hte P chain is not peptide but DNA/RNA. We should ignore such chains and do not compute conservation for them.
